# Generated by Django 6.1 on 2026-09-01 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interacoes', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='servicos.servico'),
        ),
    ]
