# Generated by Django 6.1 on 2026-09-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interacoes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
