# Generated by Django 6.1 on 2026-09-01 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='profissionais',
            field=models.ManyToManyField(blank=True, related_name='categorias', to='usuarios.profissional'),
        ),
        migrations.AddField(
            model_name='servico',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to='servicos.categoria'),
        ),
        migrations.AddField(
            model_name='servico',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='usuarios.profissional'),
        ),
    ]
